name: Java CI/CD Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Run Unit and Integration Tests
        run: mvn test
        working-directory: polishpro

      - name: Upload Test Results (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: polishpro/target/surefire-reports/

  release:
    name: Build and Upload Release JAR
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR Artifact
        run: mvn clean package -DskipTests
        working-directory: polishpro

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: polishpro-jar
          path: polishpro/target/*.jar